### ISSUE TITLE
Document CIS benchmark version.

### ISSUE THREAD

**Issue by grotewortel** [UncleSocks/onyx-caaat#10]
Hi Tyrone,

I noticed some differences in the benchmark output compared to the latest CIS IOSXE 17  benchmark (2.1.0). I think your script is based on 2.0.0.

Is it possible to document on which version of the CIS benchmark the script is based? That helps explain deviations.
Just a remark in the README.md will do. Perhaps it will help with future versioning / changelog also.

Thanks,

Jan

**Comment by UncleSocks** [comment]
Hi Jan,

Thank you for this. I actually included this information in my research paper but forgot to mention it anywhere in the repository. 

I edited the README file and should now specify which benchmark version the tool is running it against.
I also took the liberty in uploading the actual documents into the repository as well for reference.

Best regards,
Tyrone Ilisan

**Comment by grotewortel** [comment]
Great! Thank you!
