### ISSUE TITLE
Feature request: ability to run the script in non-interactive mode

### ISSUE THREAD

**Issue by grotewortel** [UncleSocks/onyx-caaat#2]
Hi UncloSocks,

I love your script and would like to use it without interaction.
This enables automation and better handling of passwords.

I have made a pull request. Please consider it.

Kind regards,

Jan

**Comment by UncleSocks** [comment]
Hey Jan, 

I just added your requested feature to the main branch. You should now be able to run 'onyx.py' without any arguments and assess multiple routers in one go. 

I opted to use a JSON file (target.json) where you can specify the following:
- IP Address
- Username
- Password
- Enable Secret/Password
- [Optional] Cisco Device Type 
- [Optional] Cisco Version

I included sample entries on target.json. I've also added a new argument to trigger the interactive mode, using '-i' (--interactive). The non-interactive setup will also automatically generate HTML reports, which can be found under 'reports_module/reports.'

Thank you, Jan.
Best regards.
