### ISSUE TITLE
output directory

### ISSUE THREAD

**Issue by grotewortel** [UncleSocks/onyx-caaat#6]
I would like to distribute the reports from the report_modules/reports directory. This directory contains 2 sample files. I removed them from that directory in my git repository. However, git does not store empty directories (it is empty before running). Therefore it does not create the output directory.

The script assumes the directory is already present.

I need to do a `mkdir -p report_modules/reports` before running the script.

Can you please look at this? :-)

**Comment by UncleSocks** [comment]
Hi Jan,

It is assumed that the script would be execute from a local machine, but it wouldn't hurt to add a mechanism to first check the existence of the reports directory and create one if it does not exist before writing the HTML reports. This would make the script more robust (although I've been planning to refactor the code down the line).

Will work on adding this mechanism.

**Comment by UncleSocks** [comment]
Mechanism has been added to ONYX. It now checks for the existence of the "reports" directory and creates one if it does not exist.
