### ISSUE TITLE
feature request: include dependency files in the HTML file

### ISSUE THREAD

**Issue by grotewortel** [UncleSocks/onyx-caaat#7]
I would like to distribute the output html file. However, it contains references to 2 .png's, a style sheet file and a javascript file.

Would it be possible to include these 4 files into the output HTML file?

I would be happy to assist. I have some examples for including PNG's as base64 in html somewhere.

Thanks you!

Jan

**Comment by UncleSocks** [comment]
Hi Jan,

CSS/JS and PNG files are now bundled during HTML report generation. You should be able to distribute the HTML report as a single file.

Regards,
Tyrone
